Oh 6 reduction plan listing
uni2growcm/openhospital-core pull request #9
Opened 2024-11-28 10:44 UTC by alvineteubo

2024-11-28 11:10 UTC, ArnaudFofou commented on sql/u2g_update/step_x_create_table_for_reductionplan.sql
> +  KEY RP_LAST_MODIFIED_BY (RP_LAST_MODIFIED_BY)
use the same way as Bill to define contraint for foreign key

2024-11-28 11:10 UTC, ArnaudFofou commented on sql/u2g_update/step_x_create_table_for_reductionplan.sql
> +)ENGINE=MyISAM;;
```suggestion
);
```

2024-11-28 11:10 UTC, ArnaudFofou commented on sql/u2g_update/step_x_create_table_for_reductionplan.sql
> +)ENGINE=MyISAM;;
```suggestion
);
```

2024-11-28 11:10 UTC, ArnaudFofou commented on sql/u2g_update/step_x_create_table_for_reductionplan.sql
> +)ENGINE=MyISAM;;
```suggestion
);
```

2024-11-28 11:11 UTC, ArnaudFofou commented on sql/u2g_update/step_x_create_table_for_reductionplan.sql
> +)ENGINE=MyISAM;;
```suggestion
);
```

2024-11-28 11:13 UTC, ArnaudFofou commented on src/main/resources/database.properties.sample
> -jdbc.url=jdbc:mariadb://localhost:3306/oh
remove this file

2024-11-28 11:14 UTC, ArnaudFofou commented on src/test/java/org/isf/reductionplan/TestsReductionplan.java
> +		@Test
please removet that Test here and add it on class Test

2024-11-28 13:40 UTC, JantBogard requested changes

2024-11-28 13:40 UTC, JantBogard commented on src/main/java/org/isf/accounting/manager/BillBrowserManager.java
Reset all change

2024-11-28 13:46 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:47 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:47 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:47 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:47 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:48 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:48 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:48 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:48 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +	}
```suggestion
	}
	
```

2024-11-28 13:52 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/model/ReductionPlan.java
> +
remove all 3 space after line 166

2024-11-28 14:23 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/manager/ReductionplanBrowserManager.java
> +	}
```suggestion
	}
	
```

2024-11-28 14:27 UTC, ArnaudFofou commented on src/test/java/org/isf/reductionplan/TestsReductionplan.java
> +
remode 2 line of space here

2024-11-28 14:27 UTC, ArnaudFofou commented on src/test/java/org/isf/reductionplan/TestsReductionplan.java
> +
```suggestion
```

2024-11-28 14:29 UTC, ArnaudFofou commented on .gitignore
> +
```suggestion
```

2024-11-28 14:30 UTC, ArnaudFofou commented on src/main/java/org/isf/reductionplan/manager/ReductionplanBrowserManager.java
> +package org.isf.reductionplan.manager;
please add doc title on all the new file

2024-11-29 08:18 UTC, ArnaudFofou commented on src/test/java/org/isf/reductionplan/TestsReductionplan.java
> +class TestsReductionplan{
```suggestion
class TestsReductionplan {
```

2024-11-29 10:44 UTC, ArnaudFofou commented
will create new PR because This PR have many work that not correspond the feature

2024-11-29 10:44 UTC, closed without merging